Inv/urls.py
from django.urls import path
from .views import CategoriaView,CategoriaNew,CategoriaEdit,CategoriaDel,SubCategoriaView,SubCategoriaNew,SubCategoriaEdit,MarcaView,MarcaNew,MarcaEdit,marca_inactivar,UMView,UMNew,UMEdit,ProductoView,ProductoNew,ProductoEdit,producto_inactivar

urlpatterns = [
     path('categorias/',CategoriaView.as_view(), name='categoria_list'),
     path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
     path('categorias/delete/<int:pk>',CategoriaDel.as_view(),
     name='categoria_del'),
     path('categorias/edit/<int:pk>',CategoriaEdit.as_view(),
     name='categoria_edit'),

     path('subcategorias/',SubCategoriaView.as_view(),
     name='subcategoria_list'),
     path('subcategorias/new',SubCategoriaNew.as_view(),
     name='subcategoria_new'),
     path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(),
     name='subcategoria_edit'),

     path('marcas/',MarcaView.as_view(),
     name='marca_list'),
     path('marcas/new',MarcaNew.as_view(),
     name='marca_new'),
     path('marcas/edit/<int:pk>',MarcaEdit.as_view(),
     name='marca_edit'),
     path('marcas/inactivar/<int:id>',marca_inactivar,
     name='marca_inactivar'),
     
     path('unidadmedidas/',UMView.as_view(),
     name='unidadmedida_list'),
     path('unidadmedidas/new',UMNew.as_view(),
     name='unidadmedida_new'),
     path('unidadmedidas/edit/<int:pk>',UMEdit.as_view(),
     name='unidadmedida_edit'),
     
     path('productos/',ProductoView.as_view(),
     name='producto_list'),
     path('productos/new',ProductoNew.as_view(),
     name='producto_new'),
     path('productos/edit/<int:pk>',ProductoEdit.as_view(),
     name='producto_edit'),
     path('productos/inactivar/<int:id>',producto_inactivar,
     name='producto_inactivar'),
     
     
   ]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('Inv/', include(('Inv.urls', 'Inv'), namespace='inv')),
    path('cmp/',include(('cmp.urls','cmp'), namespace='cmp')),
    path('admin/', admin.site.urls),
]

Inv/models.py
from django.db import models
from  bases.models import  ClaseModelo

class Categoria(ClaseModelo):
     descripcion = models.CharField(
         max_length = 100,
         help_text = 'Descripcion De La Categoria',
         unique =True
     )

     def __str__(self):
        return  '{}'.format(self.descripcion)

     def save(self):
       self.descripcion = self.descripcion.upper()
       super(Categoria, self).save()

     class Meta:
       verbose_name_plural =  "Categorias" 

    
class SubCategoria(ClaseModelo):        
     categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE
      )
     descripcion =  models.CharField(max_length = 100,help_text = "Subcategoria De Productos",unique=True)
     
     def  __str__(self):
       return '{}:{}'.format(self.categoria.descripcion,self.descripcion)
  
     def save(self):
       self.descripcion = self.descripcion.upper()
       super(SubCategoria, self).save()
     
     class Meta:
       verbose_name_plural =  "Sub Categorias"
       unique_together = ('categoria','descripcion')

class Marca(ClaseModelo):
     descripcion = models.CharField(
         max_length = 100,
         help_text = 'Descripcion De La Marca',
         unique =True
     )

     def __str__(self):
        return  '{}'.format(self.descripcion)

     def save(self):
       self.descripcion = self.descripcion.upper()
       super(Marca, self).save()

     class Meta:
       verbose_name_plural =  "Marca" 

class UnidadMedida(ClaseModelo):
      descripcion = models.CharField(
         max_length = 100,
         help_text = 'Descripcion De La Unidad Medida',
         unique =True
      )

      def __str__(self):
         return  '{}'.format(self.descripcion)

      def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

      class Meta:
        verbose_name_plural =  "Unidades De Medida" 

class Producto(ClaseModelo):
      codigo = models.CharField(
         max_length = 20,
         unique =True
      )
      codigo_barra = models.CharField(max_length=50)
      descripcion = models.CharField(max_length=200)
      precio = models.FloatField(default=0)
      existencia = models.IntegerField(default=0)
      ultima_compra = models.DateField(null=True, blank=True)  
      marca = models.ForeignKey(Marca,on_delete=models.CASCADE)
      unidad_medida = models.ForeignKey(UnidadMedida,on_delete=models.CASCADE)
      subcategoria = models.ForeignKey(SubCategoria,on_delete=models.CASCADE)

      def __str__(self):
         return  '{}'.format(self.descripcion)

      def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

      class Meta:
        verbose_name_plural =  "Productos" 
        unique_together=('codigo','codigo_barra')

bases/models.py
from django.db import models
from django.contrib.auth.models import User   

class ClaseModelo(models.Model):
      estado =  models.BooleanField(default=True)
      fc= models.DateTimeField(auto_now_add=True)
      fm= models.DateTimeField(auto_now=True)
      uc= models.ForeignKey(User, on_delete=models.CASCADE)
      um= models.IntegerField(blank=True,null=True)
      
      class  Meta:
        abstract= True
      

Inv/forms.py
from django import forms
from .models import Categoria,SubCategoria,Marca,UnidadMedida,Producto


class CategoriaForm(forms.ModelForm):
   class Meta: 
     model = Categoria
     fields = ['descripcion','estado']
     labels = {'descripcion':'Descripcion De La Categoria','estado':'Estado'}
     widget = {'descripcion': forms.TextInput}
   
   def __init__(self,*args,**kwargs):
       super().__init__(*args,**kwargs) 
       for field in iter(self.fields):
          self.fields[field].widget.attrs.update({'class':'form-control'})

class SubCategoriaForm(forms.ModelForm):
   categoria = forms.ModelChoiceField(queryset=Categoria.objects.filter(estado=True).order_by('descripcion'))
   
   class Meta: 
     model = SubCategoria
     fields = ['categoria','descripcion','estado']
     labels = {'descripcion':'Sub Categoria','estado':'Estado'}
     widget = {'descripcion': forms.TextInput}
   
   def __init__(self,*args,**kwargs):
       super().__init__(*args,**kwargs) 
       for field in iter(self.fields):
          self.fields[field].widget.attrs.update({'class':'form-control'})
       
       self.fields['categoria'].empty_label = "Seleccione Categoria"

class MarcaForm(forms.ModelForm):
      
   class Meta: 
     model = Marca
     fields = ['descripcion','estado']
     labels = {'descripcion':'Descripcion De La Marca','estado':'Estado'}
     widget = {'descripcion': forms.TextInput}
   
   def __init__(self,*args,**kwargs):
       super().__init__(*args,**kwargs) 
       for field in iter(self.fields):
          self.fields[field].widget.attrs.update({'class':'form-control'})
       
class UnidadMedidaForm(forms.ModelForm):
      
   class Meta: 
     model = UnidadMedida
     fields = ['descripcion','estado']
     labels = {'descripcion':'Descripcion De La Marca','estado':'Estado'}
     widget = {'descripcion': forms.TextInput}
   
   def __init__(self,*args,**kwargs):
       super().__init__(*args,**kwargs) 
       for field in iter(self.fields):
          self.fields[field].widget.attrs.update({'class':'form-control'})      

class ProductoForm(forms.ModelForm):
    class Meta:
      model = Producto
      fields = ['codigo','codigo_barra','descripcion','estado','precio','existencia','ultima_compra','marca','subcategoria','unidad_medida'] 
      exclude =  ['um','fm','uc','fc']
      widget = {'descripcion': forms.TextInput()}
     
    def __init__(self,*args,**kwargs):
      super().__init__(*args,**kwargs) 
      for field in iter(self.fields):
          self.fields[field].widget.attrs.update({'class':'form-control'})      
      


      self.fields['ultima_compra'].widget.attrs['readonly'] = True
      self.fields['existencia'].widget.attrs['readonly'] = True

Inv/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Categoria,SubCategoria,Marca,UnidadMedida,Producto
from .forms import CategoriaForm,SubCategoriaForm,MarcaForm,UnidadMedidaForm,ProductoForm
# Create your views here.

class CategoriaView(LoginRequiredMixin, generic.ListView):
    model = Categoria
    template_name = "inv/categoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class SubCategoriaView(LoginRequiredMixin, generic.ListView):
    model = SubCategoria
    template_name = "inv/subcategoria_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class CategoriaNew(LoginRequiredMixin, generic.CreateView):
    model= Categoria
    template_name = "Inv/categoria_form.html"
    context_object_name = "obj"
    form_class= CategoriaForm
    success_url = reverse_lazy("Inv:categoria_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.uc = self.request.user  
        return super().form_valid(form)

class CategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model= Categoria
    template_name = "Inv/categoria_form.html"
    context_object_name = "obj"
    form_class= CategoriaForm
    success_url = reverse_lazy("Inv:categoria_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.um = self.request.user.id 
        return super().form_valid(form)

class CategoriaDel(LoginRequiredMixin, generic.DeleteView):
    model= Categoria
    template_name = "Inv/catalogos_del.html"
    context_object_name = "obj"
    form_class= CategoriaForm
    success_url = reverse_lazy("Inv:categoria_list")
    
 
class SubCategoriaNew(LoginRequiredMixin, generic.CreateView):
    model= SubCategoria
    template_name = "Inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class= SubCategoriaForm
    success_url = reverse_lazy("Inv:subcategoria_list")
    login_url = "bases:login"
  
    def form_valid(self,form):
        form.instance.uc = self.request.user 
        return super().form_valid(form)

class SubCategoriaEdit(LoginRequiredMixin, generic.UpdateView):
    model= SubCategoria
    template_name = "Inv/subcategoria_form.html"
    context_object_name = "obj"
    form_class= SubCategoriaForm
    success_url = reverse_lazy("Inv:subcategoria_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.um = self.request.user.id 
        return super().form_valid(form)

class MarcaView(LoginRequiredMixin, generic.ListView):
    model = Marca
    template_name = "Inv/marca_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class MarcaNew(LoginRequiredMixin, generic.CreateView):
    model= Marca
    template_name = "Inv/marca_form.html"
    context_object_name = "obj"
    form_class= MarcaForm
    success_url = reverse_lazy("Inv:marca_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.uc = self.request.user  
        return super().form_valid(form)

class MarcaEdit(LoginRequiredMixin, generic.UpdateView):
    model= Marca
    template_name = "Inv/marca_form.html"
    context_object_name = "obj"
    form_class= MarcaForm
    success_url = reverse_lazy("Inv:marca_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.um = self.request.user.id 
        return super().form_valid(form)

def marca_inactivar(request,id):
   marca = Marca.objects.filter(pk=id).first()
   contexto = {}
   template_name = "Inv/catalogos_del.html" 
   if not  marca:
     return  redirect("Inv:marca_list")    

   if request.method=='GET':
      contexto = {'obj':marca}
   
   if request.method=='POST':
      marca.estado = False
      marca.save()
      return  redirect("Inv:marca_list")  

   return render(request,template_name,contexto)

class UMView(LoginRequiredMixin, generic.ListView):
    model = UnidadMedida
    template_name = "Inv/UnidadMedida_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class UMNew(LoginRequiredMixin, generic.CreateView):
    model= UnidadMedida
    template_name = "Inv/unidadmedida_form.html"
    context_object_name = "obj"
    form_class= UnidadMedidaForm
    success_url = reverse_lazy("Inv:unidadmedida_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.uc = self.request.user  
        return super().form_valid(form)

class UMEdit(LoginRequiredMixin, generic.UpdateView):
    model= UnidadMedida
    template_name = "Inv/unidadmedida_form.html"
    context_object_name = "obj"
    form_class= UnidadMedidaForm
    success_url = reverse_lazy("Inv:unidadmedida_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.um = self.request.user.id 
        return super().form_valid(form)

class ProductoView(LoginRequiredMixin, generic.ListView):
    model = Producto
    template_name = "Inv/producto_list.html"
    context_object_name = "obj"
    login_url = 'bases:login'

class ProductoNew(LoginRequiredMixin, generic.CreateView):
    model= Producto
    template_name = "Inv/producto_form.html"
    context_object_name = "obj"
    form_class= ProductoForm
    success_url = reverse_lazy("Inv:producto_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.uc = self.request.user  
        return super().form_valid(form)

class ProductoEdit(LoginRequiredMixin, generic.UpdateView):
    model= Producto
    template_name = "Inv/producto_form.html"
    context_object_name = "obj"
    form_class= ProductoForm
    success_url = reverse_lazy("Inv:producto_list")
    login_url = "bases:login"
     
    def form_valid(self,form):
        form.instance.um = self.request.user.id 
        return super().form_valid(form)

def producto_inactivar(request,id):
   producto = Producto.objects.filter(pk=id).first()
   contexto = {}
   template_name = "Inv/catalogos_del.html" 
   if not  producto:
     return  redirect("Inv:producto_list")    

   if request.method=='GET':
      contexto = {'obj':producto}
   
   if request.method=='POST':
      producto.estado = False
      producto.save()
      return  redirect("Inv:producto_list")  

   return render(request,template_name,contexto)

Inv/templates/Inv/catalogos_del.html
{% extends 'base/base.html' %}
{% block page_content %}
  <!-- Pending Requests Card Example -->
     <form method="POST" class="form_inline">
            {% csrf_token %}
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">¿ Eliminar {{ obj.descripcion }} ?</div>
                    <button type="submit" class="btn btn-danger"> <i class="far fa-circle"></i>Si, Eliminar</button>
                   <!-- <a href="{% url 'Inv:categoria_list'%}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> -->
                         <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> 
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                    </div>
                    <div class="col-auto">
                      <i class="far fa-circle fa-2x text-gray-300"></i>
                    </div>
                  </div>
                </div>
              </div>
            </div>
    </form>
{% endblock %}
{% block js_page %}
 
{% endblock %}

Inv/templates/Inv/categoria_form.html
{% extends 'base/base.html' %}
{% block page_content %}
     <form method="POST" class="form-inline">
              {% csrf_token %}
              <div class="col-xl-6 col-md-6 mb-6">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nueva {% endif %} Categoria
                      </div>
                      <div class="dropdown-divider"></div>
                      <div class="row">
                        <div class="col-10">
                         <div class="input-group">
                          <input type="text" name="descripcion" maxlength="100"           class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{obj.descripcion}} {% endif %}">
                         </div>
                         </div> 
                         <div class="col-2">
                          <div class="form-group">
                           <label for="id_estado">Estado</label>
                           <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}>
                          </div>
                         </div>
                      </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <a href="{% url 'Inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
{% endblock %}
{% block js_page %}
{% endblock %}

Inv/templates/Inv/categoria_list.html
{% extends 'base/base.html' %}
{% block page_content %}
              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Listado Categoria</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones</div>
                      <a class="dropdown-item" href="{% url 'Inv:categoria_new' %}"><i class="far fa-calendar-plus"></i>Nueva</a>
                      <a class="dropdown-item" href="#">Another action</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  {% if not obj %}
                   <div class="alert alert-info">No hay Categorias</div>
                  {% endif %}
                  <table class="table table-striped table-hover">
                    <thead>
                      <th>Id</th>
                      <th>Descripcion</th>
                      <th>Estado</th>
                      <th>FC</th>
                      <th>FM</th>
                      <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                      {% for item in obj %}
                       <tr> 
                          <td>{{ item.id }}</td>
                          <td>{{ item.descripcion }}</td>
                          <td>{{ item.estado |yesno:"Activo,Inactivo" }}</td>
                          <td>{{ item.fc | date:"d/m/y H:i:s"  }}</td>
                          <td>{{ item.fm | date:"d/m/y H:i:s"  }}</td>
                          <td>
                          <a href="{% url 'Inv:categoria_edit' item.id %}" class="btn btn-warning 
                          btn-circle"  role="button"><i class="far fa-edit"> 
                                                      </i></a>
                           <a href="{% url 'Inv:categoria_del' item.id %}" class="btn btn-danger 
                          btn-circle"  role="button"><i class="far fa-trash-   alt"> 
                                                      </i></a>
                          
                          </td> 
                       </tr>
                      {% endfor %}
                    </tbody>
                  </table>  
                  
                </div>
            </div>
{% endblock %}
{% block js_page %}
 <script>
  $(document).ready(function() {
    $('.table').DataTable();
  });
 </script>
{% endblock %}

Inv/templates/Inv/marca_form.html
{% extends 'base/base.html' %}
{% block page_content %}
     <form method="POST" class="form-inline">
              {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nueva {% endif %} Marca
                      </div>
                      <div class="dropdown-divider"></div>
                      <div class="row">
                     
                        <div class="col-5">
                         <div class="input-group">
                         <!-- <input type="text" name="descripcion" maxlength="100"           class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{obj.descripcion}} {% endif %}"> -->
                           {{ form.descripcion }}
                         </div>
                        </div> 
                        <div class="col-2">
                          <div class="input-group">
                           <!--  <label for="id_estado">Estado</label>
                           <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}> -->
                            {{ form.estado }} 
                          </div>
                         </div>
                      </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <a href="{% url 'Inv:marca_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
{% endblock %}
{% block js_page %}
{% endblock %}

Inv/templates/Inv/producto_form.html
<div class="modal-dialog modal-lg">
  <div class="modal-content">
     {% if obj%}
      <form method="POST" role="form" class="form-inline" action="{% url 'Inv:producto_edit' obj.pk%}">
     {% else %}
       <form method="POST" role="form" class="form-inline" action="{% url 'Inv:producto_new' %}">
     {% endif %}
              {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nueva {% endif %} Producto
                      </div>
                       <div class="row">
                          {{ form.as_p }}
                       </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <a href="{% url 'Inv:producto_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
</div>
</div>

Inv/templates/Inv/subcategoria_form.html
{% extends 'base/base.html' %}
{% block page_content %}
     <form method="POST" class="form-inline">
              {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nueva {% endif %} Sub Categoria
                      </div>
                      <div class="dropdown-divider"></div>
                      <div class="row">

                        <div class="col-5">
                         <div class="input-group">
                         <!-- <input type="text" name="descripcion" maxlength="100"           class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{obj.descripcion}} {% endif %}"> -->
                           {{ form.categoria }}
                         </div>
                        </div>
                        <div class="col-5">
                         <div class="input-group">
                         <!-- <input type="text" name="descripcion" maxlength="100"           class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{obj.descripcion}} {% endif %}"> -->
                           {{ form.descripcion }}
                         </div>
                        </div> 
                        <div class="col-2">
                          <div class="input-group">
                           <!--  <label for="id_estado">Estado</label>
                           <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}> -->
                            {{ form.estado }} 
                          </div>
                         </div>
                      </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <a href="{% url 'Inv:subcategoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
{% endblock %}
{% block js_page %}
{% endblock %}

Inv/templates/Inv/unidadmedida_form.html
{% extends 'base/base.html' %}
{% block page_content %}
     <form method="POST" class="form-inline">
              {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nueva {% endif %} Unidad Medida
                      </div>
                      <div class="dropdown-divider"></div>
                      <div class="row">
                     
                        <div class="col-5">
                         <div class="input-group">
                         <!-- <input type="text" name="descripcion" maxlength="100"           class="form-control" required id="id_descripcion" placeholder="Descripcion" value="{% if obj %} {{obj.descripcion}} {% endif %}"> -->
                           {{ form.descripcion }}
                         </div>
                        </div> 
                        <div class="col-2">
                          <div class="input-group">
                           <!--  <label for="id_estado">Estado</label>
                           <input type="checkbox" name="estado" class="form-control" id="id_estado" {% if obj.estado %} checked {% endif %}> -->
                            {{ form.estado }} 
                          </div>
                         </div>
                      </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <a href="{% url 'Inv:unidadmedida_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
{% endblock %}
{% block js_page %}
{% endblock %}