Inv/urls.py
from django.urls import path
from .views import CategoriaView,CategoriaNew,CategoriaEdit,CategoriaDel,SubCategoriaView,SubCategoriaNew,SubCategoriaEdit,MarcaView,MarcaNew,MarcaEdit,marca_inactivar,UMView,UMNew,UMEdit,ProductoView,ProductoNew,ProductoEdit,producto_inactivar

urlpatterns = [
     path('categorias/',CategoriaView.as_view(), name='categoria_list'),
     path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
     path('categorias/delete/<int:pk>',CategoriaDel.as_view(),
     name='categoria_del'),
     path('categorias/edit/<int:pk>',CategoriaEdit.as_view(),
     name='categoria_edit'),

     path('subcategorias/',SubCategoriaView.as_view(),
     name='subcategoria_list'),
     path('subcategorias/new',SubCategoriaNew.as_view(),
     name='subcategoria_new'),
     path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(),
     name='subcategoria_edit'),

     path('marcas/',MarcaView.as_view(),
     name='marca_list'),
     path('marcas/new',MarcaNew.as_view(),
     name='marca_new'),
     path('marcas/edit/<int:pk>',MarcaEdit.as_view(),
     name='marca_edit'),
     path('marcas/inactivar/<int:id>',marca_inactivar,
     name='marca_inactivar'),
     
     path('unidadmedidas/',UMView.as_view(),
     name='unidadmedida_list'),
     path('unidadmedidas/new',UMNew.as_view(),
     name='unidadmedida_new'),
     path('unidadmedidas/edit/<int:pk>',UMEdit.as_view(),
     name='unidadmedida_edit'),
     
     path('productos/',ProductoView.as_view(),
     name='producto_list'),
     path('productos/new',ProductoNew.as_view(),
     name='producto_new'),
     path('productos/edit/<int:pk>',ProductoEdit.as_view(),
     name='producto_edit'),
     path('productos/inactivar/<int:id>',producto_inactivar,
     name='producto_inactivar'),
     
     
   ]

cmp/urls.py
from django.urls import path
from .views import ProveedorView,ProveedorNew,ProveedorEdit,proveedor_inactivar

urlpatterns = [
     path('proveedores/',ProveedorView.as_view(), name='proveedor_list'),
     path('proveedores/new',ProveedorNew.as_view(), name='proveedor_new'),
     path('proveedores/edit/<int:pk>',ProveedorEdit.as_view(),
     name='proveedor_edit'),
     path('proveedores/inactivar/<int:id>',proveedor_inactivar,
     name='proveedor_inactivar'),     
     
   ]

django_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('Inv/', include(('Inv.urls', 'Inv'), namespace='inv')),
    path('cmp/',include(('cmp.urls','cmp'), namespace='cmp')),
    path('admin/', admin.site.urls),
]

cmp/models.py
from django.db import models
from  bases.models import ClaseModelo

class Proveedor(ClaseModelo):
      descripcion = models.CharField(
                    max_length = 100,
                    unique = True
                  )
      direccion = models.CharField(
                  max_length = 250,
                  null = True, blank = True
                 )    

      contacto = models.CharField(
                  max_length = 100    
                  )   
      telefono = models.CharField(
                 max_length =  10,
                 null = True, blank = True
                 ) 

  
      email = models.CharField(
              max_length = 250,
              null = True,blank=True
              )
      
      def __str__(self):
           return '{}'.format(self.descripcion)  
   
      def save(self):
           self.descripcion =  self.descripcion.upper()
           super(Proveedor, self).save()

      class Meta:
           verbose_name_plural = "Proveedores"

cmp/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    email = forms.EmailField(max_length=254)
    class Meta:
       model =  Proveedor
       exclude = ['um','fm','uc','fc'] 
       widget = {'descripcion':forms.TextInput()}
       
       def __init__(self,*args,**kwargs):
           super().__init__(*args,kwargs)
           for field in iter(self.fields):
              self.fields[field].widget.attrs.update({
                  'class':'form-control'
              })  
           

cmp/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import  reverse_lazy

from django.contrib.auth.mixins import LoginRequiredMixin
from .models  import Proveedor
from  cmp.forms import ProveedorForm
from django.http import  HttpResponse
import json

class ProveedorView(LoginRequiredMixin,generic.ListView):
      model =  Proveedor
      template_name = 'cmp/proveedor_list.html'
      context_object_name = 'obj' 
      login_url = 'bases:login'

class ProveedorNew(LoginRequiredMixin,generic.CreateView):
      model = Proveedor
      template_name = 'cmp/proveedor_form.html'
      context_name_object  = 'obj'
      form_class =  ProveedorForm
      success_url = reverse_lazy("cmp:proveedor_list")
      login_url = "bases:login" 
      
      def form_valid(self, form):
         form.instance.uc =  self.request.user
         return super().form_valid(form)
 

class ProveedorEdit(LoginRequiredMixin,generic.UpdateView):
      model = Proveedor
      template_name = "cmp/proveedor_form.html" 
      context_object_name = 'obj'
      form_class = ProveedorForm
      success_url = reverse_lazy("cmp:proveedor_list")
      login_url = "bases:login"

      def form_valid(self, form):
          form.instance.um =  self.request.user.id
          return super().form_valid(form) 

def proveedor_inactivar(request,id):
   template_name = "cmp/inactivar_prv.html" 
   contexto = {}
   proveedor = Proveedor.objects.filter(pk=id).first()
   if not  proveedor:
     return HttpResponse('Proveedor No Existe' + str(id))   

   if request.method=='GET':
      contexto = {'obj':proveedor}
   
   if request.method=='POST':
      proveedor.estado = False
      proveedor.save()
      prv.contexto = {'obj':'ok'}
      return   redirect("cmp:proveedor_list")
      #   return  HttpResponse('Proveedor Inactivado')
      

   return render(request,template_name,contexto)  
  

cmp/templates/cmp/inactivar_prv.html
 <div class="modal-dialog modal-lg">
  <div class="modal-content">
  <!-- Pending Requests Card Example -->
     <form method="POST" class="form_inline">
            {% csrf_token %}
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase">
                         <div class="alert">¿ Inactivar {{ obj.descripcion }} ?
                         </div>
                      </div>
                     <div class="row">
                       <button type="button" class="btn btn-danger" id="btninactivar"> <i class="far fa-question-circle"></i>Si, Eliminar</button>
                       <button type="button" class="btn btn-success" onclick="return cerrar_modal()"> No,Cancelar</Button>                    
                     </div>                    
                  </div>
                </div>
              </div>
            </div>
    </form>
</div>
</div> 
<script>
 $(document).ready(function(){
    var token = $('input[name=csrfmiddlewaretoken]').val();
    $.ajaxSetup({
     beforeSend: function(xhr, settings){
       if(!(/^http:.*/.test(settings.url) || /^http:.*/.test(settings.url))){
         xhr.setRequestHeader("X-CSRFToken",token);
       }
     }

    });
    $("#btninactivar").click(function(e){
      // e.preventDefault();
      // alert("Prueba de inav");
      var id = {{ obj.id }};
      var template = "{% url 'cmp:proveedor_inactivar' obj.id  %}";
      var data = {"id":id};
      data =  JSON.stringify(data);
      
      $.ajax({
        type:"POST",
        url: template,
        data : data,
        beforeSend: function(xhr, settings){ 
          $.ajaxSettings.beforeSend(xhr,settings);
        },
        success: function(response){
         console.log(response);
         cerrar_modal();
         alert(response);
        },
       
        error: function(jqXHR,textStatus,errorThrow){
          console.log(textStatus,errorThrow);
          cerrar_modal();
        }
      });     

    });

  });

</script>

cmp/templates/cmp/proveedor_form.html
<div class="modal-dialog modal-lg">
  <div class="modal-content">
     {% if obj%}
      <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_edit' obj.pk %}">
     {% else %}
       <form method="POST" role="form" class="form-inline" action="{% url 'cmp:proveedor_new' %}">
     {% endif %}
              {% csrf_token %}
              <div class="col-xl-12 col-md-12 mb-12">
              {% if obj %}
               <div class="card border-left-warning shadow h-100 py-2">
              {% else %}
               <div class="card border-left-success shadow h-100 py-2">
              {% endif %}
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                      {% if obj %} Editar {% else %} Nuevo {% endif %} Proveedor
                      </div>
                       <div class="row">
                          {{ form.as_p }}
                       </div>
                       <div class="dropdown-divider"></div>
                       <div class="row">
                        <div class="col"> 
                          <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span>Guardar</button>
                          <button type="button" class="btn btn-success" onclick=" return cerrar_modal()" >Cancelar</button>
                         
                        </div>
                       </div>
                    </div>
                  </div>
                </div>
              </div> 
             </div> 
   </form>
</div>
</div>

cmp/templates/cmp/proveedor_list.html
{% extends 'base/base.html' %}
{% block page_content %}
              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Proveedores</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">Acciones</div>
                        <a class="dropdown-item" onclick="return abrir_modal('{% url 'cmp:proveedor_new'%}')" href="#"><i class="far fa-calendar-plus"></i>Nuevo</a>                      
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  {% if not obj %}
                   <div class="alert alert-info">No hay Proveedores</div>
                  {% endif %}
                  <table class="table table-striped table-hover">
                    <thead>
                      <th>Id</th>
                      <th>Descripcion</th>
                      <th>Direccion</th>
                      <th>Contacto</th>
                      <th>Telefono</th>
                      <th>Email</th>
                      <th>Estado</th>
                      <th class="all">Acciones</th>
                    </thead>
                    <tbody>
                      {% for item in obj %}
                       <tr> 
                          
                          <td>{{ item.id}}</td>
                          <td>{{ item.descripcion }}</td>
                          <td>{{ item.direccion }}</td>
                          <td>{{ item.contacto }}</td>
                          <td>{{ item.telefono  }}</td>
                          <td>{{ item.email  }}</td>
                          <td>{{ item.estado|yesno:"Activo,Inactivo" }}</td> 
                          <td>

                          <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_edit' item.id %}')"><i class="far fa-edit"></i></button>
                          <button class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'cmp:proveedor_inactivar' item.id %}')"><i class="far fa-thumbs-down"></i></button>
                          
                          </td> 
                       </tr>
                      {% endfor %}
                    </tbody>
                  </table>  
                  
                </div>
            </div>
{% endblock %}
{% block js_page %}
 <script>
  $(document).ready(function() {
    $('.table').DataTable();
  });
 </script>
{% endblock %}